package com.example.studentclubs.ui.theme

import androidx.compose.ui.graphics.Color

val DarkContentSecondary: Color = Color(0xFF999999)
val DarkBackgroundPrimary: Color = Color(0xE6121212)
val DarkContentPrimary: Color = Color(0xFFFFFFFF)
val DarkIconPrimary: Color = Color(0xFFFFFFFF)
val DarkContentTertiary: Color = Color(0xFF666666)
val DarkOutlineOthersPure: Color = Color(0xFF121212)
val DarkOutlineOthersImmutableDark: Color = Color(0xFF121212)
val DarkBackgroundSecondary: Color = Color(0xE6242424)
val DarkOutlineSecondary: Color = Color(0xFF3E3E3E)
val DarkButtonPrimary2Default: Color = Color(0xFF80ED99)
val DarkIconTertiary: Color = Color(0xFF4C4C4C)
val DarkContentColorfulAccent: Color = Color(0xFF5CA8FE)

val LightContentSecondary: Color = Color(0xFF818AB0)
val LightBackgroundPrimary: Color = Color(0xE6FFFFFF)
val LightContentPrimary: Color = Color(0xFF121212)
val LightIconPrimary: Color = Color(0xFF121212)
val LightContentTertiary: Color = Color(0xFFBBC2D5)
val LightOutlineSecondary: Color = Color(0xFFE8EAF1)
val LightBackgroundSecondary: Color = Color(0xE6F5F6F9)
val LightOutlineOthersPure: Color = Color(0xFFFFFFFF)
val LightOutlineOthersImmutableDark: Color = Color(0xFF121212)
val LightContentColorfulAccent: Color = Color(0xFF4A91FB)
val LightButtonPrimary2Default: Color = Color(0xFF80ED99)
val LightIconTertiary: Color = Color(0xFFD7DBE6)
val maincolor=Color(0xFFDFBD43)
val bottomnavigation=Color(0xFFEDEAEA)
val mainbackgroun=Color(0xFFFFFDF4)
val jigar=Color(0xFF4D4117)